- name: Trustification
  hosts: trustification
  vars:
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-rhel10:10bfd2a4dc87118e312f22cb950ab92c8d96e752 # noqa yaml[line-length]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
